import Head from "next/head"
import{BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram, AiFillBehanceSquare, AiFillGithub} from 'react-icons/ai'
import Image from "next/image"
import codedbyliza from "../public/avatar1.png"
import { Message } from "react-awesome-shapes"

export default function Home() {
  return (
    <div>
      <Head>
        <title>CodedByLiza</title>
        <meta name="description" content="Generated by Next.js"></meta>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="arcade text-medium">CodedByLiza</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl"/></li>
              <li><a className="epilogue bg-gradient-to-r from-emerald-200 to-green-600 text-white px-4 py-2 rounded-md ml-8 text-sm" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-4xl py-2 text-emerald-600 epilogue">Liza De Guerengomba</h2>
            <h3 className="text-2xl py-1 ">Software Developer</h3>
            <p className="text-md py-5 leading-8 epilogue">Hello and welcome! A student at Grand Canyon University student pursing a B.S. in software development with a Minor in Web Design.
              Currently looking for jobs and internships opportunities in software engineering, UI/UX design, and front-end web development. 
             I have a strong interests in front-end development, graphic design, and the.net framework. Take your time and see some current projects that
               have been coded by yours truly! </p>
          </div>
          <div className="text-4xl flex justify-center gap-14 text-emerald-400">
            <a href='https://twitter.com/luvlizaa'><AiFillTwitterCircle/></a>
            <a href='https://www.linkedin.com/in/liza-de-guerengomba/'><AiFillLinkedin/></a>
            <a href='https://github.com/lizadeguereng'><AiFillGithub/></a>
            <a href='https://www.instagram.com/liza.gue/'><AiFillInstagram/></a>
            <a href='https://www.behance.net/lizadeguer'><AiFillBehanceSquare/></a>
          </div>
          <div className="relative mx-auto rounded-full w-60 h-60 mt-10 overflow-hidden">
              
              <Image src={codedbyliza} className="text-sm" layout="fill" objectFit="cover"/>
          </div>
        </section>

        <section>
          <h3 className="text-1xl py-1 text-green-600 arcade">Recent Projects</h3>
          <p className="text-md py2 leading epilogue bg">
            Since becoming a programmer, I have done different varieties of work.
             Whether thats playing around with the <span className="text-emerald-600">.NET framworks,</span> making a game using <span className="text-emerald-600">C#,</span> or creating a <span className="text-emerald-600">Springboot and ThymeLeaf </span> application. Here are some of my most recent! Enjoy!
          </p>
        </section>

      </main>
      </div> 
  )
}
