import Head from "next/head"
import{BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram} from 'react-icons/ai'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create"></meta>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="arcade text-medium">CodedByLiza</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl"/></li>
              <li><a className=" bg-gradient-to-r from-orange-200 to-orange-500 bg-orange-400 text-white px-4 py-2 rounded-md ml-8 text-sm" href="#">Resume</a></li>
            </ul>
          </nav>
          <div>
            <h2>Liza De Guerengomba</h2>
            <h3>Software Developer</h3>
            <p>A Student pursuing a Bachelor's in Science in Software Development with a Minor in Web Design.
               A programmer who is passionate about the web and everything front-end. Take your time and see some current projects I
               have been coded by yours truly! </p>
          </div>
          <div>
            <a href='https://twitter.com/luvlizaa'><AiFillTwitterCircle/></a>
            <a href='https://www.linkedin.com/in/liza-de-guerengomba/'><AiFillLinkedin/></a>
            <a href='https://www.instagram.com/liza.gue/'><AiFillInstagram/></a>
          </div>
        </section>
      </main>
      </div>
  )
}
