import Head from "next/head"
import{BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram, AiFillBehanceSquare, AiFillGithub} from 'react-icons/ai'
import Image from "next/image"
import codedbyliza from "../public/avatar1.png"
import computer from "../public/comp2.png"
import design from "../public/palette.png"
import kind from "../public/shakinghands.png"
import design1 from "../public/design1.png"
import design2 from "../public/design2.png"
import design3 from "../public/design3.png"
import design4 from "../public/design4.png"
import design5 from "../public/design5.png"
import {useState} from 'react'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>CodedByLiza</title>
        <meta name="description" content="Generated by Next.js"></meta>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className="bg-white px-10 md:px-20 dark:bg-emerald-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="arcade text-medium dark:text-white">CodedByLiza</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-white"/></li>
              <li><a className="epilogue bg-gradient-to-r from-emerald-300 to-pink-500 text-white px-4 py-2 rounded-md ml-8 text-sm" href="https://docs.google.com/document/d/1xoNSU8pAtSav0lPuUUE_jKV9-daC876N/edit?usp=sharing&ouid=113470234002244784971&rtpof=true&sd=true">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-4xl py-2 text-emerald-600 epilogue dark:text-emerald-300">Liza De Guerengomba</h2>
            <h3 className="text-2xl py-1 dark:text-white ">Software Developer</h3>
            <p className="text-sm py-5 leading-8 md:text-sm max-1-lg mx-auto epilogue dark:text-white">Hello and welcome! I am a Grand Canyon University student pursing a B.S. 
                in software<br></br> development with a Minor in Web Design. Currently looking for jobs and
                internships<br></br> opportunities in software engineering, UI/UX design, and front-end web development.
                <br></br>I have strong interests in front-end development, graphic design, and the.net<br></br> framework. 
                Take your time and see some current projects that
               have been coded by <br></br>yours truly! </p>
          </div>
          <div className="text-3xl flex justify-center gap-14 text-pink-400">
            <a href='https://twitter.com/luvlizaa'><AiFillTwitterCircle/></a>
            <a href='https://www.linkedin.com/in/liza-de-guerengomba/'><AiFillLinkedin/></a>
            <a href='https://github.com/lizadeguereng'><AiFillGithub/></a>
            <a href='https://www.instagram.com/liza.gue/'><AiFillInstagram/></a>
            <a href='https://www.behance.net/lizadeguer'><AiFillBehanceSquare/></a>
          </div>
          <div className="relative mx-auto rounded-full w-60 h-60 mt-10 overflow-hidden md:h-90 md:w-90">
              
              <Image src={codedbyliza} className="text-sm" layout="fill" objectFit="cover"/>
          </div>
        </section>
        
      <div>
        <section>
          <h3 className="text-2xl py-1 text-green-600 epilogue dark:text-emerald-300">Services</h3>
          <p className="text-sm py2 leading epilogue bg dark:text-white">
          Though I love programming, my skills don't stop there. I've done <span className="text-pink-500 dark:text-pink-300">marketing, design and mockups</span> for products, businesses and customers. I am versatile with many different applications and softwares.
          </p>
        </section>
        <div className="lg:flex gap-10 dark:text-white">
          <div className="text-center shadow-lg shadow-black p-10 rounded-2xl my-10 " >
            {/* <Image src={design} width={150} height={200}/>  */}
            <h3 text-lg font-medium pt-8 pb-2 className="epilogue text-lg" >Design Tools</h3>
            <p py-2 className="text-xs py-3 epilogue">Creating beautiful and to the point designs following your needs.</p>
            <p className="py-1 epilogue text-xs">Illustrator</p>
            <p className="py-1 epilogue text-xs">Photoshop</p>
            <p className="py-1 epilogue text-xs">After Effects</p>
            <p className="py-1 epilogue text-xs">InDesign</p>
            <p className="py-1 epilogue text-xs">Figma</p>
            <p className="py-1 epilogue text-xs">Canva</p>
          </div>
          <div className="text-center shadow-lg shadow-black p-10 rounded-2xl my-5 ">
            {/* <Image src={computer} width={100} height={100} className="container image"/>  */}
            <h3 text-lg font-medium pt-8 pb-2 className="epilogue text-lg
            ">Languages and Softwares</h3>
            <p py-2 className="text-xs py-3 epilogue">Strong foundation in programming languages and IDEs. </p>
            <p className="py-1 epilogue text-xs">Visual Studio, VS Code, Eclipse</p>
            <p className="py-1 epilogue text-xs">HTML, CSS, JavaScript, React</p>
            <p className="py-1 epilogue text-xs">Java, C#, Python, SQL, C,</p>
            <p className="py-1 epilogue text-xs">Springboot and Ubuntu Linux</p>
          </div>
          <div className="text-center shadow-lg shadow-black p-10 rounded-2xl my-10 ">
            {/* <Image src={kind} className="container image"/>  */}
            <h3 text-lg font-medium pt-8 pb-2 className="epilogue text-lg">Office Skills</h3>
            <p py-2 className="text-xs py-3 epilogue ">Whether remote or in the office, I can guarantee professional work and skills.</p>
            <p className="py-1 epilogue text-xs">Github</p>
            <p className="py-1 epilogue text-xs">Team Management</p>
            <p className="py-1 epilogue text-xs">Microsoft Suite (Outlook, Word, Excel...)</p>
            <p className="py-1 epilogue text-xs">Communicator (verbal and written) </p>
          </div>
        </div>
      </div>

        <div>
        <section>
          <h3 className="text-2xl py-4 text-green-600 epilogue dark:text-emerald-300">Recent Projects</h3>
          <p className="text-sm py2 leading epilogue bg dark:text-white">
            Since becoming a programmer, I have done different varieties of work and have coded in a number of languages, front and back end.
             Whether thats playing around with the <span className="text-pink-500 dark:text-pink-300">.NET framworks,</span> making a game using <span className="text-pink-500 dark:text-pink-300">C#,</span> or creating a <span className="text-pink-500 dark:text-pink-300">Springboot and ThymeLeaf </span> application. Here are some of my most recent! Enjoy!
          </p>
        </section>
        </div>
        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          
          <div className="basis-1/3 flex-1">
            <Image src={design1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={design5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={design2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={design3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
          </div>
        </div>
    <div>
      
    </div>
      </main>
      </div> 
  )
}
